var consts = {
  FORM_ROOM_NAME_LENGTH: 50,
  TIME_DATA_BROADCAST: 1000,
  TIME_STICK_GENERATE: 1000,

  BOARD_WIDTH: 512,
  BOARD_HEIGHT: 384,
  PLAYER_WIDTH: 32,
  PLAYER_HEIGHT: 48,
  STICK_WIDTH: 32,
  STICK_HEIGHT: 32,
};

module.exports = consts;
